wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,7 +52,14 @@ jobs:
         uses: ./
         with:
           github-token: ${{ secrets.CI_TEST_SECRET }}
+          test-mode: true
 
-      - name: Print Output
+      - name: Verify Output
         id: output
-        run: echo "${{ steps.test-action.outputs.labels }}"
+        run: |
+          # verify that the test-action output label = ["test-mode"]
+          echo "Labels: ${{ steps.test-action.outputs.labels }}"
+          if [[ "${{ steps.test-action.outputs.labels }}" != "[\"test-mode\"]" ]]; then
+            echo "test-mode not found in labels"
+            exit 1
+          fi
